name: Build and Push Docker Image

on:
  push:
    branches: 
     - br1-docker
  pull_request:   

# on:
#   push:
#     tags: 
#       - 'v*' # triggers on tags like v1.0.0, v2.1.3, etc.

#build → test → docker build → **SBOM generation** → push image → deploy


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# 1. Checkout code    
    - name: Checkout vcs repo
      uses: actions/checkout@v4

#2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

#Paizei alla Ayto ta kanei k ta 2 mazi den to 8elo giati prepei na kano sbom prota
#    - name: Build and push Docker image to docker hub
#      uses: docker/build-push-action@v5
#      with:
#        context: .
#        file: ./Dockerfile
#        push: true
#        tags: |
#          ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp:${{ github.ref_name }}

#3. Build Docker image

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp:${{ github.ref_name }} -f ./Dockerfile .

#4. Generate SBOM (Syft via Anchore sbom-action)
    # -------------------------------
    # 🔐 SBOM GENERATION (ADDED HERE)
    # -------------------------------
    - name: Generate SBOM for Docker image
      uses: anchore/sbom-action@v0.17.0 #anchore/syft-action@v0.14.0
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp:${{ github.ref_name }}
        output-file: sbom.json
        format: cyclonedx-json

    - name: Show SBOM
      run: cat sbom.json

#5. Upload SBOM artifact (for audit/compliance)
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.json
    # -------------------------------



#6. Scan SBOM with Grype (fail on critical vulns)

    - name: Scan SBOM for vulnerabilities
      uses: anchore/grype-action@v0.6.0 # (this scans the sbom)
      with:
        sbom: sbom.json
        fail-on: critical

    # - name: Vulnerability Scan (Grype)  #like Trivy, Grype scans SBOM
    #   uses: anchore/scan-action@v3 # this scan the image
    #   with:
    #     image: ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp:${{ github.ref_name }}
    #     fail-build: false

 #7. Push image to Docker Hub (only if scan passes)
    # ---------------------------------------------------------
    - name: Push Docker image
      if: success()
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp:${{ github.ref_name }}

#
# Next do the same for ACR (Azure Container Registry) if you want to push there as well
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}          